/**
 * The Phase 1 acceptance test: one XRPL Testnet Payment, attested by FDC, executing a
 * deposit into a live Coston2 ERC-4626 vault out of assets the account already holds.
 *
 * No mint anywhere in the instruction path. The account is funded beforehand, deliberately
 * and visibly, and the script prints the balance before and after so the distinction is on
 * the record. Now a thin scenario over `run.ts`, which uses only the SDK.
 *
 * Run: npm run e2e -w @memokit/executor
 *
 * Required env:
 *   PRIVATE_KEY            funded Coston2 EOA (pays the FDC fee and the execute gas)
 *   XRPL_SEED              XRPL Testnet wallet seed; the account owner
 *   MEMOKIT_DEPLOYMENT     path to deployment json (default fixtures/deployment.json)
 *   MEMOKIT_VAULT          ERC-4626 vault to deposit into
 *   MEMOKIT_DEPOSIT        amount in the asset's base units
 */
import { Contract, Interface, ZeroAddress, formatUnits } from "ethers";
import { need, runMain, type Scenario } from "./run.js";

const ERC20 = [
  "function approve(address,uint256) returns (bool)",
  "function balanceOf(address) view returns (uint256)",
  "function decimals() view returns (uint8)",
  "function symbol() view returns (string)",
];
const ERC4626 = [
  "function asset() view returns (address)",
  "function deposit(uint256,address) returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function symbol() view returns (string)",
];

const vaultAddress = need("MEMOKIT_VAULT");
const depositAmount = BigInt(need("MEMOKIT_DEPOSIT"));

const scenario: Scenario = {
  label: "vault",
  note: "ERC-4626 deposit out of assets the account already holds. Generated by executor/src/e2e.ts.",

  async build({ provider, account }) {
    const vault = new Contract(vaultAddress, ERC4626, provider);
    const assetAddress: string = await vault.asset();
    const asset = new Contract(assetAddress, ERC20, provider);
    const held: bigint = await asset.balanceOf(account);
    if (held < depositAmount) {
      throw new Error(
        `account holds ${formatUnits(held, await asset.decimals())} but the instruction deposits ` +
          `${formatUnits(depositAmount, await asset.decimals())}. Fund ${account} with ${assetAddress} first -- ` +
          `funding is deliberately outside the instruction path.`,
      );
    }
    const erc20 = new Interface(ERC20);
    const erc4626 = new Interface(ERC4626);
    return {
      feeToken: ZeroAddress,
      feeAmount: 0n,
      calls: [
        { target: assetAddress, value: 0n, data: erc20.encodeFunctionData("approve", [vaultAddress, depositAmount]) },
        { target: vaultAddress, value: 0n, data: erc4626.encodeFunctionData("deposit", [depositAmount, account]) },
      ],
    };
  },

  async snapshot({ provider, account }, blockTag) {
    const vault = new Contract(vaultAddress, ERC4626, provider);
    const asset = new Contract(await vault.asset(), ERC20, provider);
    return {
      vault: vaultAddress,
      asset: await asset.getAddress(),
      assetBalance: await asset.balanceOf(account, { blockTag }),
      shares: await vault.balanceOf(account, { blockTag }),
    };
  },
};

runMain(scenario);
