/**
 * Phase 2 payout: ONE XRPL Payment carrying a 0xFC memo produces N FTestXRP transfers to N Flare
 * addresses. The instruction is a plain `Call[]` of ERC-20 transfers, not a helper contract:
 * the memo commits only a hash, so the number of recipients costs no XRPL memo budget, and a
 * helper would add an approve step and a custody surface for no gain (see PHASE2.md).
 *
 * The executor is paid 0.1 FTestXRP out of the same balance, in the asset being moved, so the
 * account never needs a second token or any FLR. The amounts sum to exactly what the account
 * holds, so the account ends at zero: nothing is left to attribute to anything but the payout.
 *
 * Also records the no-mint check: FTestXRP's totalSupply at the block before the execute and at
 * the execute block, plus a scan of the receipt for any Transfer from the zero address.
 *
 * Run: npm run payout -w @memokit/executor   (env as e2e.ts, plus MEMOKIT_FXRP)
 */
import { Contract, Interface, Wallet, ZeroAddress, formatUnits, id, keccak256, toUtf8Bytes } from "ethers";
import { need, runMain, type Scenario } from "./run.js";

const ERC20 = ["function transfer(address,uint256) returns (bool)", "function balanceOf(address) view returns (uint256)", "function totalSupply() view returns (uint256)", "function symbol() view returns (string)"];
const TRANSFER_TOPIC = id("Transfer(address,address,uint256)");

const token = need("MEMOKIT_FXRP");
/** 6 decimals. 1.2 + 1.1 + 1.0 + 0.9 + 0.7 = 4.9 FTestXRP to recipients. */
const PAYOUTS = [1_200_000n, 1_100_000n, 1_000_000n, 900_000n, 700_000n];
const FEE = 100_000n;

/** Fixed, reproducible recipients: the same run always pays the same five addresses. */
const RECIPIENTS = PAYOUTS.map((_, i) => new Wallet(keccak256(toUtf8Bytes(`memokit-phase2-payout-recipient-${i}`))).address);

const erc20 = new Interface(ERC20);

const scenario: Scenario = {
  label: "payout",
  note: "One XRPL Payment, five FTestXRP transfers, executor paid in the moved asset. Generated by executor/src/payout.ts.",

  async build({ provider, account, relayer }) {
    const held: bigint = await new Contract(token, ERC20, provider).balanceOf(account);
    const total = PAYOUTS.reduce((a, b) => a + b, 0n) + FEE;
    if (held !== total) {
      throw new Error(`account holds ${held} but the payout plus fee is ${total}; this scenario is built to drain the account exactly`);
    }
    console.log(`paying ${PAYOUTS.length} recipients, fee ${FEE} to executor ${relayer}`);
    return {
      feeToken: token,
      feeAmount: FEE,
      calls: PAYOUTS.map((amount, i) => ({
        target: token,
        value: 0n,
        data: erc20.encodeFunctionData("transfer", [RECIPIENTS[i], amount]),
      })),
    };
  },

  async snapshot({ provider, account, relayer }, blockTag) {
    const t = new Contract(token, ERC20, provider);
    const bal = (a: string) => t.balanceOf(a, { blockTag }) as Promise<bigint>;
    return {
      token,
      totalSupply: await t.totalSupply({ blockTag }),
      account: await bal(account),
      accountNativeBalance: await provider.getBalance(account, blockTag),
      executor: await bal(relayer),
      recipients: Object.fromEntries(await Promise.all(RECIPIENTS.map(async (r) => [r, await bal(r)]))),
    };
  },

  async analyse(_ctx, { before, after, receipt }) {
    const b = before as { totalSupply: bigint; account: bigint; executor: bigint; recipients: Record<string, bigint> };
    const a = after as typeof b;
    const perRecipient = RECIPIENTS.map((r, i) => ({
      recipient: r,
      expected: PAYOUTS[i].toString(),
      before: b.recipients[r].toString(),
      after: a.recipients[r].toString(),
      delta: (a.recipients[r] - b.recipients[r]).toString(),
      ok: a.recipients[r] - b.recipients[r] === PAYOUTS[i],
    }));
    const transfers = receipt.logs
      .filter((l) => l.address.toLowerCase() === token.toLowerCase() && l.topics[0] === TRANSFER_TOPIC)
      .map((l) => ({ from: "0x" + l.topics[1].slice(26), to: "0x" + l.topics[2].slice(26), amount: BigInt(l.data).toString() }));
    const mints = transfers.filter((t) => t.from.toLowerCase() === ZeroAddress);
    const supplyUnchanged = b.totalSupply === a.totalSupply;
    const checks = {
      everyRecipientReceivedExactly: perRecipient.every((r) => r.ok),
      executorPaidInMovedAsset: a.executor - b.executor === FEE,
      accountDrainedToZero: a.account === 0n,
      transferEventsFromExecute: transfers.length,
      mintsInExecuteReceipt: mints.length,
      totalSupplyUnchangedAcrossExecuteBlock: supplyUnchanged,
    };
    console.log("\nper recipient (FTestXRP):");
    for (const r of perRecipient) console.log(`  ${r.recipient}  +${formatUnits(BigInt(r.delta), 6)}  ${r.ok ? "ok" : "MISMATCH"}`);
    console.log(`executor +${formatUnits(a.executor - b.executor, 6)}, account ${formatUnits(b.account, 6)} -> ${formatUnits(a.account, 6)}`);
    console.log(`totalSupply ${b.totalSupply} -> ${a.totalSupply}  (${supplyUnchanged ? "unchanged: no mint" : "CHANGED"})`);
    console.log(`checks: ${JSON.stringify(checks)}`);
    // Record first, fail after: a trace whose checks failed is the one worth keeping.
    if (!Object.values(checks).every((v) => v === true || typeof v === "number")) {
      console.error("A PAYOUT CHECK FAILED");
      process.exitCode = 1;
    }
    return { payout: { token, recipients: perRecipient, fee: FEE.toString(), transfers, checks } };
  },
};

runMain(scenario);
